# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roland/arm/nuvoton/M051makefile

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roland/arm/nuvoton/M051makefile

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roland/arm/nuvoton/M051makefile/CMakeFiles /home/roland/arm/nuvoton/M051makefile//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roland/arm/nuvoton/M051makefile/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dudzik.elf

# Build rule for target.
dudzik.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dudzik.elf
.PHONY : dudzik.elf

# fast build rule for target.
dudzik.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/build
.PHONY : dudzik.elf/fast

M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.o: M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.S.o
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.o

# target to build an object file
M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.S.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.S.o
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.S.o

M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.o: M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.o
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.o

# target to build an object file
M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.o
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.o

M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.i: M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.i
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.i

# target to preprocess a source file
M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.i
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.i

M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.s: M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.s
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.s

# target to generate assembly for a file
M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.s
.PHONY : M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.c.s

M051BSP/Library/StdDriver/src/gpio.o: M051BSP/Library/StdDriver/src/gpio.c.o
.PHONY : M051BSP/Library/StdDriver/src/gpio.o

# target to build an object file
M051BSP/Library/StdDriver/src/gpio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/StdDriver/src/gpio.c.o
.PHONY : M051BSP/Library/StdDriver/src/gpio.c.o

M051BSP/Library/StdDriver/src/gpio.i: M051BSP/Library/StdDriver/src/gpio.c.i
.PHONY : M051BSP/Library/StdDriver/src/gpio.i

# target to preprocess a source file
M051BSP/Library/StdDriver/src/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/StdDriver/src/gpio.c.i
.PHONY : M051BSP/Library/StdDriver/src/gpio.c.i

M051BSP/Library/StdDriver/src/gpio.s: M051BSP/Library/StdDriver/src/gpio.c.s
.PHONY : M051BSP/Library/StdDriver/src/gpio.s

# target to generate assembly for a file
M051BSP/Library/StdDriver/src/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/M051BSP/Library/StdDriver/src/gpio.c.s
.PHONY : M051BSP/Library/StdDriver/src/gpio.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dudzik.elf.dir/build.make CMakeFiles/dudzik.elf.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dudzik.elf"
	@echo "... M051BSP/Library/Device/Nuvoton/M051Series/Source/GCC/startup_M051Series.o"
	@echo "... M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.o"
	@echo "... M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.i"
	@echo "... M051BSP/Library/Device/Nuvoton/M051Series/Source/system_M051Series.s"
	@echo "... M051BSP/Library/StdDriver/src/gpio.o"
	@echo "... M051BSP/Library/StdDriver/src/gpio.i"
	@echo "... M051BSP/Library/StdDriver/src/gpio.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

